### ISSUE TITLE
/time_region_value: enhance the schema's schema

### ISSUE THREAD

**Issue by mindrones** [nestauk/svizzle#411]
We are currently documenting fields using YAML comments:

```yaml
auth_provider: string|URL # OPTIONAL - in case the source is not public, the name of the organization providing source access or a URL of a web page where to get or require access, e.g. Nesta, or https://www.foo.com/get_auth
data_date: Date_YYYYMMDD # OPTIONAL - the date of the data processing, e.g. 20201213
description: string # OPTIONAL - a long description of the indicator: this is useful for a non-expert audience to have some short explanations about the data limitations (E.g. on Higher Edu R&D, they might wonder why we only have data for parts of the country), and foibles (e.g. on area of university site they may wonder about the Inner London West spike of 2016)
```

This isn't great to get or set information, e.g. the max length of a value in a certain field.
We could use a specific format but then we'd also need to parse comments, which would be cumbersome and prone to errors.

We could instead use something like this:

```yaml
auth_provider:
  type: string|URL
  optional: true
  description: in case the source is not public, the name of the organization providing source access or a URL of a web page where to get or require access, e.g. Nesta, or https://www.foo.com/get_auth
data_date:
  type: Date_YYYYMMDD
  optional: true
  description: the date of the data processing, e.g. 20201213
description:
  type: string
  optional: true
  max_len: 400 # max amount of chars
  description: 'a long description of the indicator: this is useful for a non-expert audience to have some short explanations about the data limitations (E.g. on Higher Edu R&D, they might wonder why we only have data for parts of the country), and foibles (e.g. on area of university site they may wonder about the Inner London West spike of 2016)'
```
